@echo off
cd /d "%~dp0"
echo Installing Playwright browsers (if needed)...
C:\Python314\python.exe -m playwright install chromium >nul 2>&1
echo Running E2E tests...
C:\Python314\python.exe -m pytest tests/e2e/test_live_e2e.py tests/e2e/test_smart_scraper.py tests/e2e/test_superdrugs.py tests/e2e/test_all_workflows.py -v --tb=short %*
