"""Canonical error codes for the Zero Checksum Public API."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Machine-readable error codes returned in API error envelopes."""

    INVALID_URL = "INVALID_URL"
    INVALID_SCHEMA = "INVALID_SCHEMA"
    INVALID_API_KEY = "INVALID_API_KEY"
    API_KEY_EXPIRED = "API_KEY_EXPIRED"
    API_KEY_REVOKED = "API_KEY_REVOKED"
    SCOPE_INSUFFICIENT = "SCOPE_INSUFFICIENT"
    RATE_LIMITED = "RATE_LIMITED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    SCRAPE_FAILED = "SCRAPE_FAILED"
    CRAWL_FAILED = "CRAWL_FAILED"
    SEARCH_FAILED = "SEARCH_FAILED"
    EXTRACT_FAILED = "EXTRACT_FAILED"
    WEBHOOK_DELIVERY_FAILED = "WEBHOOK_DELIVERY_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
