"""initial schema: tasks, policies, sessions, runs, results, artifacts

Revision ID: 590780df3897
Revises: 
Create Date: 2026-03-23 09:24:33.183488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590780df3897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_domains', sa.JSON(), nullable=False),
    sa.Column('preferred_lane', sa.String(length=50), nullable=False),
    sa.Column('extraction_rules', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.JSON(), nullable=False),
    sa.Column('proxy_policy', sa.JSON(), nullable=False),
    sa.Column('session_policy', sa.JSON(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('robots_compliance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('cookies', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('proxy_id', sa.String(length=36), nullable=True),
    sa.Column('browser_profile_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_domain'), 'sessions', ['domain'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_tenant_created', 'tasks', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index('ix_tasks_tenant_status', 'tasks', ['tenant_id', 'status'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('connector', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('proxy_used', sa.String(length=255), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_task_id'), 'runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('normalization_applied', sa.Boolean(), nullable=False),
    sa.Column('dedup_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_task_id'), 'results', ['task_id'], unique=False)
    op.create_index(op.f('ix_results_tenant_id'), 'results', ['tenant_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_result_id'), 'artifacts', ['result_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_result_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_results_tenant_id'), table_name='results')
    op.drop_index(op.f('ix_results_task_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_task_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_tasks_tenant_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index('ix_tasks_tenant_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_domain'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
