"""
AWS WAF Token Manager — manage aws-waf-token cookie lifecycle for Amazon scraping.

Amazon uses AWS WAF as its primary anti-bot defense. After solving a JS challenge
or CAPTCHA, the browser receives an encrypted `aws-waf-token` cookie that must
accompany all subsequent requests. Key properties:

- Token expires after ~5 minutes
- Contains a hash of the browser fingerprint — changing fingerprint invalidates it
- IP changes during a session can trigger re-verification
- The token is generated by obfuscated JavaScript that's frequently updated

This module tracks token state per domain and handles refresh/expiry.

Usage:
    waf = AWSWAFTokenManager()
    waf.store_token("amazon.com", "aws-waf-token=abc123...")
    if waf.has_valid_token("amazon.com"):
        cookies = waf.get_token_cookies("amazon.com")
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Optional

logger = logging.getLogger(__name__)

# AWS WAF token typically expires after 5 minutes
DEFAULT_TOKEN_TTL = 300

# Domains known to use AWS WAF
AWS_WAF_DOMAINS = {
    "amazon.com", "amazon.co.uk", "amazon.de", "amazon.fr", "amazon.it",
    "amazon.es", "amazon.ca", "amazon.co.jp", "amazon.in", "amazon.com.au",
    "amazon.com.br", "amazon.nl", "amazon.sg", "amazon.sa", "amazon.ae",
    "amazon.com.mx", "amazon.pl", "amazon.se", "amazon.com.be",
    "primevideo.com", "whole foods market.com", "aws.amazon.com",
}

# Cookie names that AWS WAF uses
WAF_COOKIE_NAMES = {"aws-waf-token", "aws-waf-verify"}


@dataclass
class WAFToken:
    """A stored AWS WAF token for a domain."""

    domain: str
    cookies: dict[str, str]  # cookie_name -> cookie_value
    fingerprint_hash: str  # Hash of device profile used when token was acquired
    acquired_at: float = 0.0
    ttl: float = DEFAULT_TOKEN_TTL
    refresh_count: int = 0

    @property
    def is_expired(self) -> bool:
        return time.time() - self.acquired_at > self.ttl

    @property
    def age_seconds(self) -> float:
        return time.time() - self.acquired_at

    @property
    def remaining_seconds(self) -> float:
        return max(0, self.ttl - self.age_seconds)


class AWSWAFTokenManager:
    """Manage AWS WAF tokens per domain.

    Handles:
    - Token storage and retrieval
    - Expiry detection (5-minute TTL)
    - Fingerprint consistency checking (token invalidates if fingerprint changes)
    - Pre-emptive refresh (refresh before expiry to avoid interruption)
    """

    def __init__(self, token_ttl: float = DEFAULT_TOKEN_TTL) -> None:
        self._tokens: dict[str, WAFToken] = {}  # domain -> WAFToken
        self._token_ttl = token_ttl

    @staticmethod
    def is_waf_domain(url: str) -> bool:
        """Check if a URL belongs to an AWS WAF-protected domain."""
        from urllib.parse import urlparse
        domain = urlparse(url).netloc.lower().replace("www.", "")
        return any(domain.endswith(d) for d in AWS_WAF_DOMAINS)

    @staticmethod
    def _domain_from_url(url: str) -> str:
        from urllib.parse import urlparse
        domain = urlparse(url).netloc.lower()
        if domain.startswith("www."):
            domain = domain[4:]
        return domain

    def store_token(
        self,
        domain: str,
        cookies: dict[str, str],
        fingerprint_hash: str = "",
    ) -> None:
        """Store a WAF token acquired after solving a challenge.

        Args:
            domain: The domain the token is for (e.g. "amazon.com")
            cookies: Cookie dict containing aws-waf-token and any related cookies
            fingerprint_hash: Hash of the device profile used (for consistency check)
        """
        # Filter to only WAF-relevant cookies
        waf_cookies = {}
        for name, value in cookies.items():
            if name.lower() in WAF_COOKIE_NAMES or "waf" in name.lower():
                waf_cookies[name] = value

        if not waf_cookies:
            # Store all cookies if no WAF-specific ones found (some sites use custom names)
            waf_cookies = cookies

        domain = domain.lower().replace("www.", "")
        self._tokens[domain] = WAFToken(
            domain=domain,
            cookies=waf_cookies,
            fingerprint_hash=fingerprint_hash,
            acquired_at=time.time(),
            ttl=self._token_ttl,
        )
        logger.debug(
            "Stored WAF token for %s (%d cookies, TTL=%ds)",
            domain, len(waf_cookies), int(self._token_ttl),
        )

    def store_from_browser_cookies(
        self,
        url: str,
        browser_cookies: list[dict[str, Any]],
        fingerprint_hash: str = "",
    ) -> None:
        """Store WAF tokens extracted from a Playwright browser context's cookies.

        Args:
            url: The URL that was accessed
            browser_cookies: List of cookie dicts from context.cookies()
            fingerprint_hash: Device profile hash
        """
        domain = self._domain_from_url(url)
        cookie_dict = {}
        for c in browser_cookies:
            name = c.get("name", "")
            value = c.get("value", "")
            if name and value:
                cookie_dict[name] = value

        if cookie_dict:
            self.store_token(domain, cookie_dict, fingerprint_hash)

    def has_valid_token(self, domain: str, fingerprint_hash: str = "") -> bool:
        """Check if we have a valid (non-expired) token for a domain.

        Args:
            domain: Domain to check
            fingerprint_hash: Current fingerprint hash (if provided, checks consistency)
        """
        domain = domain.lower().replace("www.", "")
        token = self._tokens.get(domain)
        if not token:
            return False
        if token.is_expired:
            return False
        # If fingerprint changed, token is invalid
        if fingerprint_hash and token.fingerprint_hash and fingerprint_hash != token.fingerprint_hash:
            logger.debug(
                "WAF token for %s invalidated (fingerprint changed)", domain
            )
            return False
        return True

    def needs_refresh(self, domain: str, buffer_seconds: float = 60.0) -> bool:
        """Check if a token should be pre-emptively refreshed.

        Returns True if the token exists but will expire within buffer_seconds.
        Pre-emptive refresh avoids interruptions during scraping.
        """
        domain = domain.lower().replace("www.", "")
        token = self._tokens.get(domain)
        if not token:
            return True  # No token — definitely need one
        return token.remaining_seconds < buffer_seconds

    def get_token_cookies(self, domain: str) -> dict[str, str]:
        """Get the WAF token cookies for a domain.

        Returns empty dict if no valid token exists.
        """
        domain = domain.lower().replace("www.", "")
        token = self._tokens.get(domain)
        if not token or token.is_expired:
            return {}
        return dict(token.cookies)

    def invalidate(self, domain: str) -> None:
        """Invalidate a token (e.g. after getting a 403 despite having a token)."""
        domain = domain.lower().replace("www.", "")
        if domain in self._tokens:
            del self._tokens[domain]
            logger.debug("Invalidated WAF token for %s", domain)

    def get_stats(self) -> dict[str, Any]:
        """Get token stats for all domains."""
        stats = {}
        for domain, token in self._tokens.items():
            stats[domain] = {
                "expired": token.is_expired,
                "age_seconds": int(token.age_seconds),
                "remaining_seconds": int(token.remaining_seconds),
                "cookie_count": len(token.cookies),
                "refresh_count": token.refresh_count,
            }
        return stats

    def clear(self) -> None:
        """Clear all stored tokens."""
        self._tokens.clear()
